version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
      - MongoDBSettings__DatabaseName=EmployeeDb
      - MongoDBSettings__CollectionName=employees
      - Redis__Host=redis
      - Redis__Port=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
